sudo: required
language: php
services:
  - docker
env:
  - CURATOR_DO_COVERAGE=1
install: composer install
script:
  - ./docker-all_tests.sh --coverage
after_success:
  # php-coveralls expects paths in the clover xml to exist
  - sudo ln -s $(pwd) /curator
  - travis_retry vendor/bin/coveralls -v
