version: '2'
services:
  phpunit_runner_7_1:
    image: curatorwik/docker_test_env
    environment:
      - PHP_VERSION=7.1.0
      - PHPUNIT=/usr/local/bin/phpunit-5.5
    volumes:
      - .:/curator
      - /tmp:/host_tmp
      - php-builds:/usr/local/phpenv/versions
    tmpfs:
      - /tmp

  phpunit_runner_7_0:
    image: curatorwik/docker_test_env
    environment:
      - PHP_VERSION=7.0.14
      - PHPUNIT=/usr/local/bin/phpunit-5.5
    volumes:
      - .:/curator
      - /tmp:/host_tmp
      - php-builds:/usr/local/phpenv/versions
    tmpfs:
      - /tmp

  phpunit_runner_5_6:
    image: curatorwik/docker_test_env
    environment:
      - PHP_VERSION=5.6.29
      - PHPUNIT=/usr/local/bin/phpunit-5.5
    volumes:
      - .:/curator
      - /tmp:/host_tmp
      - php-builds:/usr/local/phpenv/versions
    tmpfs:
      - /tmp

  phpunit_runner_5_5:
    image: curatorwik/docker_test_env
    environment:
      - PHP_VERSION=5.5.38
    volumes:
      - .:/curator
      - /tmp:/host_tmp
      - php-builds:/usr/local/phpenv/versions
    tmpfs:
      - /tmp

  phpunit_runner_5_4:
    image: curatorwik/docker_test_env
    environment:
      - PHP_VERSION=5.4.45
    volumes:
      - .:/curator
      - /tmp:/host_tmp
      - php-builds:/usr/local/phpenv/versions
    tmpfs:
      - /tmp

volumes:
  php-builds: {}
