<?php
/**
 * @file
 *   Contains base annotation for autogenerated swagger API specification.
 */

/**
 * @SWG\Swagger(
 *   @SWG\Info(
 *     version="1.0.0",
 *     title="Curator API",
 *     description="Operations of the Curator Web Install Kit.",
 *   ),
 *   produces={"application/json"},
 * )
 */
